name: CI

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.1
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.PAT }}
        run: git config --global url."https://DexterHD:${TOKEN}@github.com".insteadOf "https://github.com"

      - name: Build
        run: make build
